# https://kubernetes.io/docs/concepts/configuration/secret/#:~:text=The%20following%20example%20configuration%20declares%20a%20ServiceAccount%20token%20Secret
# ustdeki adresden kopyalayip düzenledik
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret  
type: Opaque
data:
  mysql-root-password: UjEyMzRy
  mysql-admin-password: Q2xhcnVzd2F5XzE=