# kubectl expose deploy mysql-deploy --port=3306 --target-port=3306 --dry-run=client -o yaml > mysql-service.yaml
# üsteki komutu kullandigimizda bu file direk folderda file olarak olusturuyoruz. Mükemmel
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-deploy
  name: mysql-deploy
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-deploy

